version: '3'

services:
  backend-mock:
    image: node:14-alpine
    container_name: backend_mock
    working_dir: /app
    volumes:
      - ./scripts/backend_mock:/app
    environment:
      - NODE_ENV=dev
    command: npm start
    ports:
      - '3000:3000'
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - backend-mock
    environment:
      - NODE_ENV=dev
    ports:
      - '8080:8080'
  