version: '3'

services:
  backend:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./scripts/backend:/app
    environment:
      - NODE_ENV=dev
    command: npm start
    ports:
      - '3000:3000'
  app:
    build:
      context: .
    depends_on:
      - backend
    environment:
      - NODE_ENV=dev
    ports:
      - '8080:8080'
  